[versions]
java = "<%= javaVersion %>"
kotlin = "<%= kotlinVersion %>"
boot = "<%= springBootVersion %>"

[libraries]

[plugins]
springframework-boot = { id = "org.springframework.boot", version.ref = "boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version = "1.1.0" }
github-khalilou88-jnxplus = { id = "io.github.khalilou88.jnxplus", version = "0.2.0" }
jetbrains-kotlin-plugin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

