name: Check plugin
on:
  workflow_dispatch:
    inputs:
      framework:
        type: choice
        description: Framework
        options:
          - boot
          - quarkus
          - micronaut
      buildTool:
        type: choice
        description: Build Tool
        options:
          - maven
          - maven-bom
          - gradle
          - gradle-kt
      os:
        type: choice
        description: Os
        options:
          - ubuntu-latest
          - macOS-latest
          - windows-latest

jobs:
  Run_checks:
    strategy:
      matrix:
        node_version: ['18']
        java: ['17']
      fail-fast: true
    runs-on: ${{ github.event.inputs.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'npm'

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Install dependencies
        run: npm ci

      - name: Unit tests
        run: npm run test nx-${{ github.event.inputs.framework }}-${{ github.event.inputs.buildTool }}

      - name: Build
        run: npm run build nx-${{ github.event.inputs.framework }}-${{ github.event.inputs.buildTool }}

      - name: E2E tests
        run: npm run e2e nx-${{ github.event.inputs.framework }}-${{ github.event.inputs.buildTool }}-e2e
        env:
          NX_VERBOSE_LOGGING: 'true'
          GITHUB_ACTIONS: 'true'
