name: Run plugin smoke tests
on:
  workflow_dispatch:
    inputs:
      t_option:
        type: choice
        description: t option
        options:
          - nx-gradle micronaut smoke
          - nx-gradle default smoke
          - nx-gradle quarkus smoke
          - nx-gradle spring-boot smoke
          - nx-maven micronaut smoke
          - nx-maven default smoke
          - nx-maven quarkus smoke
          - nx-maven spring-boot smoke
      os:
        type: choice
        description: Os
        options:
          - ubuntu-latest
          - macOS-latest
          - windows-latest

jobs:
  run_plugin_smoke_tests:
    name: Running ${{ github.event.inputs.t_option }} smoke tests from ${{ github.head_ref || github.ref_name }} branch
    strategy:
      matrix:
        node_version: ['18']
        java: ['17']
      fail-fast: true
    runs-on: ${{ github.event.inputs.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'npm'

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Install dependencies
        run: npm i --legacy-peer-deps

      - name: smoke tests
        run: npm run nx smoke jnxplus-smoke -- --t="${{ github.event.inputs.t_option }}"
        env:
          NX_VERBOSE_LOGGING: 'true'
          GITHUB_ACTIONS: 'true'
          MAVEN_ARGS: '-Dmaven.plugin.validation=VERBOSE'
