name: Publish nx-boot-maven
on: [workflow_dispatch]
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@3

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build nx-boot-maven

      - name: Setup .npmrc file to publish to npm
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Publish
        run: npm publish dist/packages/nx-boot-maven
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
